### ISSUE TITLE
Just tried this with 3.0 Canary

### ISSUE THREAD

**Issue by lgleasain** [keyboardsurfer/btt-android-studio-config#1]
Sad Panda.  Are you using a different version or am I doing something else wrong?

**Comment by keyboardsurfer** [comment]
Did you follow the instructions and have imported the config into BetterTouchTool?

**Comment by sebastianmarschall** [comment]
Does not work with **Android Studio 3.0 Canary 8**, i followed the instructions and imported to BTT

**Comment by keyboardsurfer** [comment]
Please try with Canary 9. I can't reproduce your issue with that version.
