### ISSUE TITLE
Can't import config to BTT's preset

### ISSUE THREAD

**Issue by excitedhaha** [keyboardsurfer/btt-android-studio-config#6]
Error message : Sorry, the preset couldn't be imported as it seems to be in the wrong format.

**Comment by keyboardsurfer** [comment]
I'm using a BTT 2.3.11 at the moment and it works. At some point there was a change in the config files of BTT. Please make sure that you're using a recent version of it.

**Comment by excitedhaha** [comment]
Thanks for your reply, Mine is 2.310

**Comment by keyboardsurfer** [comment]
AFAIK this version should already support the "new format".
I just re-imported the configuration and BTT does not complain.
Have you made modifications or are we talking about a clean clone from this repository?

**Comment by excitedhaha** [comment]
It seems that i did not download the right file , now things have been clear . Thank you
