### ISSUE TITLE
Doesn't work on OSX 10.13 with AS 3.0.1

### ISSUE THREAD

**Issue by dkej123** [keyboardsurfer/btt-android-studio-config#8]
Hi, 

I went through installation step but it doesn't work. 

osx version: 10.13
Android Studio version 3.0.1

**Comment by keyboardsurfer** [comment]
Make sure that touchbar controls are enabled for BTT.
3.0.1 definitely works for others and myself. Maybe you'll have to re-start BTT.

**Comment by dkej123** [comment]
Hi, 
I resolved my problem. I don't know why it did not work. After few restarts of btt it started working correctly
